### ISSUE TITLE
a chat box

### ISSUE THREAD

**Issue by budi** [ryanb/govsgo#38] opened 2010-11-15 20:06 UTC
lots of trolls will invade the chat box, but I usually talk about the game I played after the game is finished. I think it would be fun to discuss it right on the site (even when the game is still playing) using a chat box. a simple one will suffice.

budi from Indonesia.
cheers.

**Comment by ryanb** [comment] 2010-11-15 21:23
Thanks for this suggestion. Closing this because it's duplicate of issue #10.

**Closed as completed by ryanb** 2010-11-15 21:23 UTC
